# === REQUIRED ===
owner: arki-tech            # your GitHub username/org
repo: arki-uptime           # this repo's name
user-agent: arki-tech       # optional but recommended

# Monitors (edit these)
sites:
  - name: ARKI Uptime
    url: https://api.getarki.com/v1/heartbeat
    headers:
      - "Accept: application/json"
  # Example with secret header:
  # - name: Protected API
  #   url: https://api.example.com/health
  #   headers:
  #     - "Authorization: Bearer $API_TOKEN"   # add API_TOKEN in repo Secrets

# Status website config (NO CNAME since you're using github.io/<repo>)
status-website:
  baseUrl: /arki-uptime
  logoUrl: https://static.wixstatic.com/media/8ae53d_9d2fee1d8a5f42f2ad7d380aef5c2346~mv2.png/v1/fill/w_48,h_46,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/ARKI-A-Square-Favicon.png
  name: Arki Status
  introTitle: "**Arki Status** — uptime & response time"
  introMessage: "Powered by Upptime (GitHub Actions, Issues, and Pages)."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  footer: "ARKI DIGITAL INC."

# (Optional) schedules, notifications, etc. can go below
# See https://upptime.js.org/docs/configuration
