# === REQUIRED ===
owner: arki-tech            # your GitHub username/org
repo: arki-uptime           # this repo's name
user-agent: arki-tech       # optional but recommended

# Monitors (edit these)
sites:
  - name: ARKI Uptime
    url: https://api.getarki.com/v1/heartbeat
    headers:
      - "Accept: application/json"
  # Example with secret header:
  # - name: Protected API
  #   url: https://api.example.com/health
  #   headers:
  #     - "Authorization: Bearer $API_TOKEN"   # add API_TOKEN in repo Secrets

# Status website config
status-website:
  cname: status.getarki.com

  logoUrl: https://static.wixstatic.com/media/8ae53d_9d2fee1d8a5f42f2ad7d380aef5c2346~mv2.png/v1/fill/w_48,h_46,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/ARKI-A-Square-Favicon.png
  favicon: https://status.getarki.com/assets/arki-square-32x32.png
  name: ARKI Status
  introTitle: "**ARKI Status** — uptime & response time"
  introMessage: "ARKI Platform Status"
  navbar:
    - title: Status
      href: /
    - title: ARKI App
      href: https://app.getarki.com

  footer: "ARKI DIGITAL INC."

# (Optional) schedules, notifications, etc. can go below
# See https://upptime.js.org/docs/configuration
