# === REQUIRED ===
owner: arki-tech            # your GitHub username/org
repo: arki-uptime           # this repo's name
user-agent: arki-tech       # optional but recommended

# Monitors (edit these)
sites:
  - name: ARKI API
    url: https://api.getarki.com/v1/heartbeat
    headers:
      - "Accept: application/json"
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Hacker News
    url: https://news.ycombinator.com
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co
  - name: IPv6 test
    check: tcp-ping
    url: forwardemail.net
    port: 80
    ipv6: true
  # Example with secret header:
  # - name: Protected API
  #   url: https://api.example.com/health
  #   headers:
  #     - "Authorization: Bearer $API_TOKEN"   # add API_TOKEN in repo Secrets

# Status website config (NO CNAME since you're using github.io/<repo>)
status-website:
  baseUrl: /arki-uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Arki Status
  introTitle: "**Arki Status** — uptime & response time"
  introMessage: "Powered by Upptime (GitHub Actions, Issues, and Pages)."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# (Optional) schedules, notifications, etc. can go below
# See https://upptime.js.org/docs/configuration
